# This job is to test different maven profiles in sdk branch again Pull Request raised
# This workflow targets Java with Maven execution

name: Java SDK Test workflow for Maven on workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'The pull request number to build'
        required: true

jobs:
  comment-run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        java: [ '8', '11', '17' ]
        os: [ 'ubuntu-latest', 'macos-latest', 'macos-11' ]
    name: Local Repo ${{ matrix.Java }} - ${{ matrix.os }}
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.inputs.pull_request_number }}/head
      - name: Fetch Commit SHA
        run: |
          git log -1 --format='%H'
          echo "commit_sha=$(git log -1 --format='%H')" >> $GITHUB_ENV
          echo "commit_sha=$(git log -1 --format='%H')" >> $env:GITHUB_ENV
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Run mvn test
        run: |
          mkdir $HOME/.browserstack
          chmod -R 777 $HOME/.browserstack
          mvn compile
          mvn test
      - if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Local Repo ${{ matrix.Java }} - ${{ matrix.os }}
          path: ./src/test/logs.txt
